#!/bin/bash

#############################################
# https://github.com/sitemapxml/USet        #
# Author: Виктор Павловић                   #
#         https://github.com/sitemapxml     #
# License: MIT                              #
# Publish date: Aug 2, 2020.                #
# Version: 2.4.0                            #
#############################################

# Load configuration and libraries
source 'config.txt'
source 'libraries/args.sh'

# Read arguments
if [ "$#" = 0 ]; then
  echo "Running script in interactive mode..."
  sleep 1s
else
  source 'includes/arglist.inc.sh'
fi

# Load definied language and if file does not exist revert to en.txt
if [ -f "languages/$conf_language.txt" ]; then
  source "languages/$conf_language.txt"
else
  source 'languages/en.txt'
fi
if [ -f "languages/welcome/$conf_language.txt" ]; then
  source "languages/welcome/$conf_language.txt"
else
  source 'languages/welcome/en.txt'
fi
if [ -f "languages/help/$conf_language.txt" ]; then
  source "languages/help/$conf_language.txt"
else
  source 'languages/help/en.txt'
fi

# Load functions
source 'includes/functions.inc.sh'
source 'includes/input.inc.sh'
source 'includes/install.inc.sh'

case "$1" in
  -h) printf "$lang_help" && exit 1 ;;
  --help) printf "$lang_help" && exit 1 ;;
esac

# Turn output text coloring On or Off
if [ "$conf_disable_colors" = "true" ]; then
  fn_output_coloring_off
else
  fn_output_coloring_on
fi

# Gives execute rights to uninstall script
chmod +x 'tools/uninstall'

if [ "$conf_skip_welcome_screen" = "true" ]; then
  :
else
  # Welcome screen!
  whiptail --title "USet" --scrolltext --msgbox "$lang_welcome" 20 65 || echo "$lang_welcome"
fi

# Input data
[ -n "$hostname" ] && printf "hostname already set to ${YELLOW}$hostname${NC}, skipping user input...\n" || fn_input_hostname
[ -n "$rootpass" ] && printf "rootpass already set, skipping user input...\n" || fn_input_rootpass
[ -n "$unixuser" ] && printf "unixuser already set to ${YELLOW}$unixuser${NC}, skipping user input...\n" || fn_input_unixuser
[ -n "$unixpass" ] && printf "unixpass already set, skipping user input...\n" || fn_input_unixpass
[ -n "$mysqlrpass" ] && printf "mysqlrpass already set, skipping user input...\n" || fn_input_mysqlrpass
[ -n "$email" ] && printf "email already set to ${YELLOW}$email${NC}, skipping user input...\n" || fn_input_email
[ -n "$web_server" ] && printf "web_server already set to ${YELLOW}$web_server${NC}, skipping user input...\n" || fn_input_server_type

# Main installation process
fn_install

# Install SSL Certificate
fn_install_ssl

# Install Adminer
[ "$conf_install_adminer" = 'true' ] && fn_install_adminer
# UFW firewall
[ "$conf_enable_ufw" = 'true' ] && fn_enable_ufw
# Creating password backup file
[ "$conf_create_pass_backup" = 'true' ] && fn_create_pass_backup

# Post-installation messages
fn_msg_completed

# Deleting bash and mysql history
fn_delete_history
