#!/bin/bash

# Definicije boja
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

# Reset boja - No Color
NC='\033[0m'

while true
	do
	echo -e ${YELLOW}'Korak (1/*)'${NC}
	read -p 'Da li želite da uklonite Universe repozitoriju? (Da/Ne): ' uninstall_universe
		case $uninstall_universe in
		[dD][aA]|[dD])
			echo 'Uklanjanje...'
			# Uklanjanje universe repozitorije
			add-apt-repository --remove universe
			touch /etc/apt/sources.list
			apt-get update
			add-apt-repository main
			echo -e ${GREEN}'Universe repozitorija je onemogućena!'${NC}
		break
		;;
		[nN][eE]|[nN])
	break
	;;
	*)
	echo -e ${RED}'Molimo vas da odgovorite sa Da ili Ne.'${NC}
	;;
	esac
done

while true
	do
	echo -e ${YELLOW}'Korak (2/*)'${NC}
	read -p 'Da li želite da deinstalirate apache vebserver? (Da/Ne): ' uninstall_ssl
		case $uninstall_ssl in
		[dD][aA]|[dD])
			echo 'Deinstalacija je u toku...'
			# Deinstalacija apache servera
			apt-get purge apache2 apache2-utils -y
			apt-get autoremove --purge -y

			# Uklanjanje preostalih direktorijuma
			rm -rf /usr/sbin/apache2
			rm -rf /usr/lib/apache2
			rm -rf /etc/apache2
			rm -rf /usr/share/man/man8/apache2.8.gz
			echo -e ${GREEN}'Apache veb server je deinstaliran!'${NC}
		break
		;;
		[nN][eE]|[nN])
	break
	;;
	*)
	echo -e ${RED}'Molimo vas da odgovorite sa Da ili Ne.'${NC}
	;;
	esac
done

while true
	do
	echo -e ${YELLOW}'Korak (3/*)'${NC}
	read -p 'Da li želite da deinstalirate PHP? (Da/Ne): ' uninstall_php
		case $uninstall_php in
		[dD][aA]|[dD])
			echo 'Deinstalacija je u toku...'
			# Uklanjanje php-a
			apt-get purge 'php*' -y
			apt-get autoremove
			apt-get autoclean
			echo -e ${GREEN}'PHP je deinstaliran!'${NC}
		break
		;;
		[nN][eE]|[nN])
	break
	;;
	*)
	echo -e ${RED}'Molimo vas da odgovorite sa Da ili Ne.'${NC}
	;;
	esac
done

while true
	do
	echo -e ${YELLOW}'Korak (4/*)'${NC}
	read -p 'Da li želite da deinstalirate MYSQL server? (Da/Ne): ' uninstall_mysql
		case $uninstall_mysql in
		[dD][aA]|[dD])
			echo 'Deinstalacija je u toku...'
			# Deinstalacija mysql servera
			systemctl stop mysql
			apt-get --yes purge mysql-server mysql-client
			apt-get --yes autoremove --purge
			apt-get autoclean

			# Uklanjanje preostalih direktorijuma
			rm /etc/apparmor.d/abstractions/mysql
			rm /etc/apparmor.d/cache/usr.sbin.mysqld

			# Brisanje mysql istorije
			rm ~/.mysql_history
			
			# Brisanje istorije svih mysql korisnika na sistemu
			awk -F : '{ print($6 "/.mysql_history"); }' /etc/passwd | xargs -r -d '\n' -- sudo rm -f --

			# Brisanje log fajlova izvan postojećih home direktorijuma
			find / -name .mysql_history -delete
			echo -e ${GREEN}'MYSQL server je deinstaliran!'${NC}
		break
		;;
		[nN][eE]|[nN])
	break
	;;
	*)
	echo -e ${RED}'Molimo vas da odgovorite sa Da ili Ne.'${NC}
	;;
	esac
done

while true
	do
	echo -e ${YELLOW}'Korak (5/*)'${NC}
	read -p 'Da li želite da onemogućite zaštitu portova? (Da/Ne): ' uninstall_ufw
		case $uninstall_ufw in
		[dD][aA]|[dD])
			echo 'Deinstalacija je u toku...'
			
			# Onemogući UFW
			ufw --force disable
			echo -e ${GREEN}'Zaštitni zid je onemogućen!'${NC}
		break
		;;
		[nN][eE]|[nN])
	break
	;;
	*)
	echo -e ${RED}'Molimo vas da odgovorite sa Da ili Ne.'${NC}
	;;
	esac
done
